#!/bin/bash
#
# This is a rather minimal example Argbash potential
# Example taken from http://argbash.readthedocs.io/en/stable/example.html
#
# ARG_OPTIONAL_SINGLE([directory],[d],[root directory to search through],["$HOME"/Music])
# ARG_POSITIONAL_MULTI([pattern],[search pattern],[2],[.])
# ARG_OPTIONAL_SINGLE([max-results],[n],[maximum number of results returned],[all])
# ARG_OPTIONAL_BOOLEAN([first],[1],[limit to the first result found],[off])
# ARG_HELP()
# ARGBASH_SET_INDENT([  ])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die() {
  local _ret="${2:-1}"
  test "${_PRINT_HELP:-no}" = yes && print_help >&2
  echo "$1" >&2
  exit "${_ret}"
}


begins_with_short_option() {
  local first_option all_short_options='dn1h'
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_pattern=('' ".")
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_directory="$HOME"/Music
_arg_max_results="all"
_arg_first="off"


print_help()
{
  printf 'Usage: %s [-d|--directory <arg>] [-n|--max-results <arg>] [-1|--(no-)first] [-h|--help] <pattern-1> [<pattern-2>]\n' "$(basename $0)"
  printf '\t%s\n' "<pattern>: search pattern; the 2nd search pattern is applied on the full path"
  printf '\t%s\n' "-d, --directory: root directory to search through (default: '"$HOME"/Music')"
  printf '\t%s\n' "-n, --max-results: maximum number of results returned (default: all)"
  printf '\t%s\n' "-1, --first, --no-first: limit to the first result found, ignores --max-results if set"
  printf '\t%s\n' "-h, --help: prints help"
}


parse_commandline()
{
  _positionals_count=0
  while test $# -gt 0
  do
    _key="$1"
    case "$_key" in
      -d|--directory)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_directory="$2"
        shift
        ;;
      --directory=*)
        _arg_directory="${_key##--directory=}"
        ;;
      -d*)
        _arg_directory="${_key##-d}"
        ;;
      -n|--max-results)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_max_results="$2"
        shift
        ;;
      --max-results=*)
        _arg_max_results="${_key##--max-results=}"
        ;;
      -n*)
        _arg_max_results="${_key##-n}"
        ;;
      -1|--no-first|--first)
        _arg_first="on"
        test "${1:0:5}" = "--no-" && _arg_first="off"
        ;;
      -1*)
        _arg_first="on"
        _next="${_key##-1}"
        if test -n "$_next" -a "$_next" != "$_key"
        then
          { begins_with_short_option "$_next" && shift && set -- "-1" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
        fi
        ;;
      -h|--help)
        print_help
        exit 0
        ;;
      -h*)
        print_help
        exit 0
        ;;
      *)
        _last_positional="$1"
        _positionals+=("$_last_positional")
        _positionals_count=$((_positionals_count + 1))
        ;;
    esac
    shift
  done
}


handle_passed_args_count()
{
  local _required_args_string="'pattern'"
  test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require between 1 and 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
  test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 1 and 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
  local _positional_name _shift_for=$1
  _positional_names="_arg_pattern[0] _arg_pattern[1] "

  shift "$_shift_for"
  for _positional_name in ${_positional_names}
  do
    test $# -gt 0 || break
    eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
    shift
  done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# Reconcile --max-results and --first
if [[ "$_arg_first" == "on" ]]; then
  _arg_max_results=1
fi
