#!/bin/bash

set -euo pipefail

source src/utils.sh
source src/arg-parse.sh

echo "$_arg_directory"
echo ${_arg_pattern[*]}
find_songs ${_arg_pattern[*]} "$_arg_directory" | xargs --no-run-if-empty --open-tty -d "\n" mplayer || message_empty "songs"
