#!/bin/bash

set -euo pipefail

source src/utils

MUSIC_DIR="$HOME"/Music

play() {
  if [[ "$(find "$1" -maxdepth 1 -name "*.m3u" -print -quit)" ]]; then
    play_playlist "$1"
  else
    play_all_files "$1"
  fi
}

play_playlist() {
  fdfind --type f --glob "*m3u" "$1" | xargs --open-tty -d "\n" mplayer -playlist
}

play_all_files() {
  mplayer "$1"*
}

main() {
  find_albums "$@" > /dev/null || (message_empty "albums" && exit 0)
  album_dirs="$(find_albums "$@")"
  echo -e "Found $(wc -l <<< "$album_dirs") album(s):\n$album_dirs\n"

  IFS=$'\n'
  for dir_ in $album_dirs; do
    play "$dir_"
  done
}


main "$@"
